In [1]:
import numpy as np

In [2]:
def pathfinder(a,residual):

    
    
    seen=[False]*len(a)
    queue=[0] #contains all the seen nodes
    seen[0]=True
    allpath={}
    while queue:
        last=queue.pop(0)
        for i,val in enumerate(residual[last]):
            if val>0:
                if seen[i]==False:
                    seen[i]=True
                    queue.append(i)
                    if a[last,i]>0:
                        allpath[i]=(last,'forward')
                    if a[i,last]>0:
                        allpath[i]=(last,'backward')
                    if i==len(a)-1:
                        key=list(allpath.keys())
                        back=key[-1]
                        path=[back]
                        while back!=0:
            
                            back=allpath[back][0]
                            path.append(back)
                        
                        return True, path,allpath
                    
    
    return False ,[], allpath

In [3]:
def residualflowchange(a,x,residual,path,allpath):
    epsilon=max([max(a[i]) for i in range(len(a))])
    for i in range(len(path)-1):
        epsilon=min(epsilon,residual[path[i+1],path[i]])
    if epsilon>0:
        for i in range(len(path)-1):
            if allpath[path[i]][1]=='forward':
                x[path[i+1],path[i]]= x[path[i+1],path[i]]+epsilon
                x[path[i],path[i+1]]= -x[path[i+1],path[i]]
            
            if allpath[path[i]][1]=='backward':
                x[path[i+1],path[i]]= -(x[path[i],path[i+1]]-epsilon)
                x[path[i],path[i+1]]= -x[path[i+1],path[i]]
            
            residual[path[i+1],path[i]]= a[path[i+1],path[i]]-x[path[i+1],path[i]]
            residual[path[i],path[i+1]]= a[path[i],path[i+1]]-x[path[i],path[i+1]]
        print(path,epsilon)
        print('residual',residual)
        print('x',x)
    return x,residual
    

In [4]:
def Optimizer(a):
    x=np.zeros((len(a),len(a)))
    residual=np.zeros((len(a),len(a)))

    result=pathfinder(a,residual)
    
    if result[0]==True:
        while result[0]:
            x=residualflowchange(a,x,residual,result[1],result[2])[0]
            residual=residualflowchange(a,x,residual,result[1],result[2])[1]
            result=pathfinder(a,residual)
        
    return x
        

In [5]:
a=np.zeros((6,6))
a[0,1]=9
a[0,2]=15
a[2,1]=0
a[1,2]=0
a[2,3]=5
a[1,3]=0
a[2,4]=6
a[4,5]=17
a[3,5]=17
a[4,3]=0
a[1,4]=10
#path=pathfinder(a,a)[1]
#allpath=pathfinder(a,a)[2]
#print(residualflowchange(a,np.zeros((6,6)),a,path,allpath)[0])

print(Optimizer(a))

val from 0 to 0 0.0
val from 0 to 1 9.0
val from 0 to 2 15.0
val from 0 to 3 0.0
val from 0 to 4 0.0
val from 0 to 5 0.0
val from 1 to 0 0.0
val from 1 to 1 0.0
val from 1 to 2 0.0
val from 1 to 3 0.0
val from 1 to 4 10.0
val from 1 to 5 0.0
val from 2 to 0 0.0
val from 2 to 1 0.0
val from 2 to 2 0.0
val from 2 to 3 5.0
val from 2 to 4 6.0
val from 2 to 5 0.0
val from 4 to 0 0.0
val from 4 to 1 0.0
val from 4 to 2 0.0
val from 4 to 3 0.0
val from 4 to 4 0.0
1
[5, 4, 1, 0] 9.0
residual [[ 0.  0. 15.  0.  0.  0.]
 [ 9.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  5.  6.  0.]
 [ 0.  0.  0.  0.  0. 17.]
 [ 0.  9.  0.  0.  0.  8.]
 [ 0.  0.  0.  0.  9.  0.]]
x [[ 0.  9.  0.  0.  0.  0.]
 [-9.  0.  0.  0.  9.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0. -9.  0.  0.  0.  9.]
 [ 0.  0.  0.  0. -9.  0.]]
val from 0 to 0 0.0
val from 0 to 1 0.0
val from 0 to 2 15.0
val from 0 to 3 0.0
val from 0 to 4 0.0
val from 0 to 5 0.0
val from 2 to 0 0.0
val from 2 to 1 0.0
val from 2 to 2 0.0
v